name: Publish Grass Clicker to Itch.io

on:
 push:
  branches:
  - main
 pull_request:
  branches:
  - main
env:
 BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }} # Needs to be added through github
 DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # Needs to be added through github
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 IS_MAIN: ${{ contains(github.ref, 'main') }}
 PROJECT_NAME: "Grass Clicker"

jobs:
 CleanArtifacts:
  # This job clears out the previous artifacts made so you don't run out of space in your github account
  runs-on: ubuntu-latest
  steps:
  - uses: kolpav/purge-artifacts-action@v1
    with:
     token: ${{ secrets.GITHUB_TOKEN }}
     expire-in: 1hr

 Export:
  needs: CleanArtifacts # wait for artifacts to clean before making a new one
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - name: Download + Authorize Godot
    run: |
       curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.4-rc1/Godot_v4.4-rc1_linux.x86_64.zip
       unzip godot.zip
       mv Godot_v4.4-rc1_linux.x86_64 godot
       ls
       chmod +x godot
 
  - name: Download Export Templates
    run: |
     curl -L -o export_templates.zip https://github.com/godotengine/godot-builds/releases/download/4.4-rc1/Godot_v4.4-rc1_export_templates.tpz
     unzip export_templates.zip
  
  - name: Install Export Templates
    run: |
     mkdir -p ~/.local/share/godot/export_templates/4.4.rc1
     mv ./templates/* ~/.local/share/godot/export_templates/4.4.rc1
  
  - name: Export Web
    run: |
     mkdir -p ./build/web
     ./godot --headless --path ./ --export-release "Web" ./build/web/index.html
    
  - name: Export Windows Desktop
    run: |
     mkdir -p ./build/win
     ./godot --headless --path ./ --export-release "Windows Desktop" ./build/win/game.exe
    
  - name: Export Linux
    run: |
     mkdir -p ./build/linux
     ./godot --headless --path ./ --export-release "Linux" ./build/linux/game.x86_64
    

  - uses: actions/upload-artifact@v4
    with:
     name: exports
     path: exports

 Publish:
  needs: Export
  if: ${{ contains(github.ref, 'main') }}
  runs-on: ubuntu-latest
  steps:
    - uses: actions/download-artifact@v4
    
    - name: Download + Authorize Butler
      run: |
       curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
       unzip butler.zip
       chmod +x butler
       ./butler -V
    
    - name: Login To Butler
      run: ./butler login

    - name: Push Web to Itch
      run: ./butler push ./build/web cyteon/grass-clicker:web --userversion-file ./VERSION/VERSION.txt
    
    - name: Push Windows Desktop to Itch
      run: ./butler push ./build/win cyteon/grass-clicker:win --userversion-file ./VERSION/VERSION.txt
    
    - name: Push Linux to Itch
      run: ./butler push ./build/linux cyteon/grass-clicker:linux --userversion-file ./VERSION/VERSION.txt
    


 Cleanup:
  needs: [Export, Publish]
  runs-on: ubuntu-latest
  steps:
    - uses: geekyeggo/delete-artifact@v1
      with:
       name: VERSION
